project:
  name: "GIS-BI Nepal"
  offline_mode: true
  base_dir: ".."             
  data_dir: "../data"        
  h3_resolution: 7           
  month_slice: "latest"      

region:
  name: "Nepal"
  bbox: [80.0586, 26.347, 88.2015, 30.4469]

indices:
  A_index:
    weights:
      viirs_z: 0.60
      built_delta: 0.25
      road_dens_delta: 0.15
    z_cap: 3.0
  N_index:
    weights:
      ndvi_z: 0.50
      rain_z: 0.30
      fire_z: 0.20
    z_cap: 3.0

admin_rollups:
  enabled: true
  sources:
    - name: "geoBoundaries-NPL-ADM2"  
      level: "adm2"
    - name: "geoBoundaries-NPL-ADM1"  
      level: "adm1"

datasets:
  viirs:
    kind: "raster"
    product: "VIIRS_DNB_monthly"
    notes: "Night lights radiance; monthly; used for A-index (z-score)"
  modis_ndvi:
    kind: "raster"
    product: "MODIS_MOD13A2_1km_16day"
    notes: "NDVI (16-day); monthly mean to N-index"
  modis_fire:
    kind: "vector_or_raster"
    product: "MODIS_FIRE"
    notes: "Monthly fire detections count per H3"
  chirps:
    kind: "raster"
    product: "CHIRPS_0p05"
    notes: "Monthly rainfall sum; anomaly to Shockboard & N-index"
  worldcover:
    kind: "raster"
    product: "ESA_WorldCover_10m_2020_2021"
    notes: "Static built-up share; delta across years"
  ghsl:
    kind: "raster"
    product: "GHSL_BUILT_S2"
    notes: "Built-up proxy (static/epochal)"
  srtm:
    kind: "raster"
    product: "SRTM_30m"
    notes: "Static elevation/slope mask (context)"
  osm_roads:
    kind: "vector"
    product: "OSM_roads_geofabrik"
    notes: "Optional: monthly diffs later; disabled by default for speed"

client:
  slice_fields:
    anthropological: ["A_index", "viirs_z", "built_share", "road_km_density"]
    natural: ["N_index", "ndvi_z", "rain_z", "fire_density"]
  color_bins: 7
  export_formats: ["csv", "geojson", "parquet"]

runtime:
  threads: 4
  chunk_mb: 128
  temp_dir: "../data/tmp"
